// <auto-generated />
using CatalogOnline.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogOnline.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240509170346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogOnline.DAL.DBO.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("legal_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("user_id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
