// <auto-generated />
using CatalogOnline.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogOnline.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogOnline.DAL.DBO.Course", b =>
                {
                    b.Property<int>("course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("course_id"));

                    b.Property<int>("credits_number")
                        .HasColumnType("int");

                    b.Property<bool>("mandatory")
                        .HasColumnType("bit");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("course_id");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("CatalogOnline.DAL.DBO.Grade", b =>
                {
                    b.Property<int>("grade_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("grade_id"));

                    b.Property<int>("course_id")
                        .HasColumnType("int");

                    b.Property<double>("percentage")
                        .HasColumnType("float");

                    b.Property<double>("score")
                        .HasColumnType("float");

                    b.Property<string>("type_of_exam")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("grade_id");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("CatalogOnline.DAL.DBO.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("legal_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("user_id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
